# Generated by Django 4.0.4 on 2022-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile_remove_userstate_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
