# Generated by Django 4.0.4 on 2022-05-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_events_private_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
