# Generated by Django 4.0.4 on 2022-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_userprofile_department_service_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='libelle',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
